config/routes.rb
StockCorr::Application.routes.draw do
  resources :stocks
  root to: 'stocks#index'
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :stock_histories
end

app/models/stock_history.rb
class StockHistory < ActiveRecord::Base
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.page params[:page]
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "StockCorr"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") StockCorr
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013

app/views/stocks/_form.html.haml
= form_for @stock, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :symbol, :class => 'control-label'
    .controls
      = f.text_field :symbol, :class => 'text_field'
  .control-group
    = f.label :open, :class => 'control-label'
    .controls
      = f.text_field :open, :class => 'text_field'
  .control-group
    = f.label :high, :class => 'control-label'
    .controls
      = f.text_field :high, :class => 'text_field'
  .control-group
    = f.label :low, :class => 'control-label'
    .controls
      = f.text_field :low, :class => 'text_field'
  .control-group
    = f.label :close, :class => 'control-label'
    .controls
      = f.text_field :close, :class => 'text_field'
  .control-group
    = f.label :volume, :class => 'control-label'
    .controls
      = f.text_field :volume, :class => 'text_field'
  .control-group
    = f.label :stock_data, :class => 'control-label'
    .controls
      = f.text_field :stock_data, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), stocks_path, :class => 'btn'

app/views/stocks/edit.html.haml
- model_class = Stock
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stocks/index.html.haml
- model_class = Stock
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

= paginate @stocks

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:symbol)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:open)
      %th= model_class.human_attribute_name(:high)
      %th= model_class.human_attribute_name(:low)
      %th= model_class.human_attribute_name(:close)
      %th= model_class.human_attribute_name(:volume)
  %tbody
    - @stocks.each do |stock|
      %tr
        %td= link_to stock.symbol, stock
        %td= stock.name
        %td= number_to_currency stock.open
        %td= number_to_currency stock.high || stock.stock_data['days_high']
        %td= number_to_currency stock.low || stock.stock_data['days_low']
        %td= number_to_currency stock.close || stock.stock_data['previous_close']
        %td= number_with_delimiter stock.volume

= paginate @stocks

app/views/stocks/new.html.haml
- model_class = Stock
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stocks/show.html.haml
- model_class = Stock
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:symbol) + ':'
  %br
  = @stock.symbol
%p
  %strong= model_class.human_attribute_name(:open) + ':'
  %br
  = @stock.open
%p
  %strong= model_class.human_attribute_name(:high) + ':'
  %br
  = @stock.high
%p
  %strong= model_class.human_attribute_name(:low) + ':'
  %br
  = @stock.low
%p
  %strong= model_class.human_attribute_name(:close) + ':'
  %br
  = @stock.close
%p
  %strong= model_class.human_attribute_name(:volume) + ':'
  %br
  = @stock.volume
%p
  %strong= model_class.human_attribute_name(:stock_data) + ':'
  %br
  = @stock.stock_data

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), stocks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_stock_path(@stock), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), stock_path(@stock), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'